### ISSUE TITLE
Stable pearl rename crash

### ISSUE THREAD

**Issue by EvieTheOwl** [KnowYourKnot/Enderporter#2]
Enderporter stable pearl can be renamed to crash the server

**Server crash**: https://gist.github.com/profjb58/f59688f2cece6215b95a77b2f00c3a24
**Client crash**: https://gist.github.com/profjb58/3ca63fe6a35840dc57062cfc6a920a07

![](https://media.discordapp.net/attachments/814452859273216070/815266292541030460/unknown.png)

Client crash happens when a user hovers over the pearls name. Submitted by ThatTrollzer (CoolMineMan) in the Tiny Tater Test server crashathon thingy.

**Comment by KnowYourKnot** [comment]
Fixed in 1.0.2
